# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import student_gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_gallery', '0004_auto_20160106_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='a@s.com', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(default='awe', upload_to=student_gallery.models.getResume),
        ),
        migrations.AddField(
            model_name='profile',
            name='studentId',
            field=models.CharField(default='awe', max_length=20),
        ),
    ]
