# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_gallery', '0008_auto_20160112_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_info',
        ),
    ]
