# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import student_gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_gallery', '0010_student_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='audio_track',
            field=models.FileField(default='', upload_to=student_gallery.models.getAudio),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='email',
            field=models.EmailField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='pic',
            field=models.ImageField(upload_to=student_gallery.models.getImage),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='resume',
            field=models.FileField(default='', upload_to=student_gallery.models.getResume),
        ),
    ]
