# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
