# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import sample_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=120)),
                ('imagePath', models.FileField(upload_to=sample_app.models.getImage)),
                ('imageDescription', models.CharField(max_length=300)),
            ],
        ),
    ]
