# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='discription',
        ),
    ]
