# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import gallery_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery_app', '0007_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pic', models.ImageField(upload_to=gallery_app.models.getImage)),
                ('discription', models.CharField(max_length=500)),
                ('audio_track', models.FileField(upload_to=gallery_app.models.getAudio)),
                ('video_track', models.FileField(default='qwe', upload_to=gallery_app.models.getVideo)),
            ],
        ),
    ]
