# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import student_gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pic', models.FileField(upload_to=student_gallery.models.getImage)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
