# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_gallery', '0005_auto_20160107_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='studentId',
        ),
    ]
