# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import student_gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_gallery', '0009_delete_student_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(default='a@s.com', max_length=60)),
                ('pic', models.ImageField(upload_to=student_gallery.models.getImage)),
                ('discription', models.CharField(max_length=500)),
                ('audio_track', models.FileField(upload_to=student_gallery.models.getAudio)),
                ('video_track', models.FileField(default='', upload_to=student_gallery.models.getVideo)),
                ('resume', models.FileField(default='awe', upload_to=student_gallery.models.getResume)),
            ],
        ),
    ]
